# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='custom_url',
            field=models.BooleanField(default=False),
        ),
    ]
