# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_proposal_custom_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='ip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
