# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-31 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vote_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='video_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='youtube id'),
        ),
    ]
